### PR TITLE
Added pair programming rotations CSV

### PR DESCRIPTION
**Pull request by bonellon**

### CODE REVIEW

**Review by Jamesxu182 — DISMISSED** [review]

**Review by zihan0 — COMMENTED** [review]
something is missing

**Review by zihan0 — DISMISSED** [review]
great work xx

**Comment by bonellon** [comment]
> something is missing

**Review by GrennanM — APPROVED** [review]

**Review by GrennanM — CHANGES_REQUESTED** [review]
place rotations into separate folder

**Comment by bonellon** [comment]
@GrennanM Added PairRotations folder 💯 💯

**Comment by bonellon** [comment]
@GeeseHoward Pls stop ignoring emails and review the PR

**Comment by zihan0** [comment]
> place rotations into separate folder

**Comment by GeeseHoward** [comment]
Looks good.

**Review by GeeseHoward — DISMISSED** [review]

**Comment by ats0stv** [comment]
@bonellon The file name could be something like `Team3-TrinityWayfinders-PairRotations.xlsx` or something or that order

**Review by ats0stv — CHANGES_REQUESTED** [review]
* Name of the file `Team3-TrinityWayfinders-PairRotations.xlsx`
* It would be good if the document is reformatted in a easily printable manner - more of a vertical fashion in portrait mode

**Review by ats0stv — APPROVED** [review]

**Comment by ats0stv** [comment]
@GrennanM you may want to approve the changes since the changes you requested has been made

**Review by GrennanM — APPROVED** [review]

**Pull request merged**
