### PR TITLE
WD-8: first commit

### PR DESCRIPTION
**Pull request by zihan0**

### CODE REVIEW

**Review by ats0stv — CHANGES_REQUESTED** [review]
1. Please change the commit message to WD-8: First commit <of what>
2. User Mgmt: Upgrade a user level - What are the levels of the user? Have something in mind?
3. Notification Management - Admin should be able to push a notification to a 'user'. He/she should be able only to publish notifications to a set / all of users (Banner/Disaster Alerts, etc.,)
4. Why does one of the UCD has <<include>> and the other it is not noted?
5. Access User Account --> 'View Usage' spelling
6. User --> Delete account should also be available
7. Access User Profile --> It would be good to mention about user goals as well
8. Why is only guest having an option to choose from options and not the regular user
9. Are the use cases modelled for all the users

**Comment by bonellon** [comment]
Where is the superadmin?

**Comment by bonellon** [comment]
https://en.oxforddictionaries.com/definition/usage

**Review by bonellon — DISMISSED** [review]

**Comment by GrennanM** [comment]
Just a couple of spellings: 'inactive' under admin should be 'inactivate' and 'discription' under user should be 'description.' Otherwise, looks good to me.

**Review by GrennanM — APPROVED** [review]
Looks good!

**Review by ats0stv — APPROVED** [review]

**Pull request merged**
